# UR16eMoverService.srv

# --- Request ---
geometry_msgs/Pose target_pose
bool use_cartesian
---
# --- Response ---
bool success
string error_message
moveit_msgs/RobotTrajectory trajectory
float64 planned_fraction
